export const PROFILE_LIST_REQUEST = "PROFILE_LIST_REQUEST";
export const PROFILE_LIST_SUCCESS = "PROFILE_LIST_SUCCESS";
export const PROFILE_LIST_FAIL = "PROFILE_LIST_FAIL";
export const CLEAN_PROFILE_LIST = "CLEAN_PROFILE_LIST";

export const PROFILE_DETAILS_REQUEST = "PROFILE_DETAILS_REQUEST";
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
export const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_FAIL";
export const CLEAN_PROFILE_DETAILS = "CLEAN_PROFILE_DETAILS";

export const GET_MORE_PROJECTS_REQUEST = "GET_MORE_PROJECTS_REQUEST";
export const GET_MORE_PROJECTS_SUCCESS = "GET_MORE_PROJECTS_SUCCESS";
export const GET_MORE_PROJECTS_FAIL = "GET_MORE_PROJECTS_FAIL";
